apiVersion: v1
kind: Pod
metadata:
  name: arslanansari-20453-redis-pod
  labels:
    name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 2045
